name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        APP: ["actions-aliyun-cli", "actions-alpine-tools"]
    steps:
    - uses: actions/checkout@master
    - name: build docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build ${{ matrix.APP }} -t pintia/${{ matrix.APP }}:latest
        docker push pintia/${{ matrix.APP }}:latest
